services:
  madr_database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"

  madr_app:
    image: madr
    entrypoint: ./entrypoint.sh
    build: .
    environment:
      DATABASE_URL: postgresql+psycopg://app_user:app_password@madr_database:5432/app_db
      SECRET_KEY: "secure secret key"
      ALGORITHM: "HS256"
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
    ports:
      - "8000:8000"
    depends_on:
      - madr_database

volumes:
  pgdata: