"""add not null constraint to users and novelists

Revision ID: 5bd57142ab29
Revises: 13c4ab97f776
Create Date: 2024-08-30 12:15:53.192941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bd57142ab29'
down_revision: Union[str, None] = '13c4ab97f776'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email', nullable=False)
    op.alter_column('users', 'username', nullable=False)
    op.alter_column('users', 'password', nullable=False)
    op.alter_column('novelists', 'name', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email', nullable=True)
    op.alter_column('users', 'username', nullable=True)
    op.alter_column('users', 'password', nullable=True)
    op.alter_column('novelists', 'name', nullable=True)
    # ### end Alembic commands ###
